services:
  mautrix-telegram:
    container_name: mautrix-telegram
    image: dock.mau.dev/mautrix/telegram:latest
    restart: unless-stopped
    networks:
      - matrix-backend
      - mautrix-internal
    volumes:
      - /opt/mautrix/telegram:/data
  db:
    image: postgres:latest
    restart: always
    networks:
      - mautrix-internal
    environment:
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_USER: mautrix
      POSTGRES_DB: mautrix_telegram
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data:

networks:
  mautrix-internal:
  matrix-backend:
    external: true