services:
  mautrix-discord:
    container_name: mautrix-discord
    image: dock.mau.dev/mautrix/discord:latest
    depends_on: 
      - db
    restart: unless-stopped
    networks:
      - matrix-backend
      - mautrix-internal
    volumes:
    - ./data:/data
  db:
    image: postgres:latest
    restart: always
    networks:
      - mautrix-internal
    environment:
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_USER: mautrix
      POSTGRES_DB: mautrix_discord
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data:

networks:
  mautrix-internal:
  matrix-backend:
    external: true